# Generated by Django 4.2 on 2023-04-12 13:48

import computed_property.fields
import counts.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uk_election_ids.election_ids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, validators=[uk_election_ids.election_ids.validate])),
                ('date', computed_property.fields.ComputedDateField(compute_from='_date', editable=False)),
                ('org', computed_property.fields.ComputedCharField(compute_from='_org', editable=False, max_length=32)),
                ('constituency', computed_property.fields.ComputedCharField(compute_from='_constituency', editable=False, max_length=32, null=True)),
                ('quota', models.IntegerField(default=None, null=True)),
            ],
            options={
                'ordering': ['date', 'org', 'constituency'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('party_id', models.CharField(max_length=32)),
                ('party_name', models.CharField(max_length=32)),
                ('standing', models.ManyToManyField(to='counts.ballot')),
            ],
            options={
                'ordering': ['party_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, validators=[uk_election_ids.election_ids.validate])),
                ('date', computed_property.fields.ComputedDateField(compute_from='_date', editable=False)),
                ('org', computed_property.fields.ComputedCharField(compute_from='_org', editable=False, max_length=32)),
            ],
            options={
                'ordering': ['date', 'org'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=counts.utils.uuidv6, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('count_stage', models.IntegerField()),
                ('non_transferable', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('evidence_url', models.URLField(null=True, verbose_name='Paste a link to evidence of this count stage (twitter picture/etc)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counts.ballot')),
                ('validated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StageCell',
            fields=[
                ('id', models.UUIDField(default=counts.utils.uuidv6, editable=False, primary_key=True, serialize=False, unique=True)),
                ('count', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counts.candidate')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counts.stage')),
            ],
        ),
        migrations.AddField(
            model_name='ballot',
            name='election',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='counts.election'),
        ),
    ]
